server:
  port: 9090

spring:
  application:
    name:


  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 1111

  profiles:
    active: local

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true